//! OpenVINO backend for the dense MLP of Inkling's first layers, all rows of a
//! frame in one device call.
//!
//! Once every MoE layer of a pipeline rank runs fused on the iGPU, rank 0 is
//! the slowest stage of the fleet: its two dense layers (intermediate 24576,
//! 226 MB of int4 each) stay on the CPU, 60 ms of a 230 ms frame at 16 rows on
//! a 25 W box. The IR is three compressed MatMuls (the bins' own nibbles and
//! scales, like the fused MoE layers) with a dynamic row count:
//! `x [1, rows, hidden] -> down(silu(gate x) * up x) -> y [1, rows, hidden]`,
//! generated by `tools/inkling_moe_layer_ov.py --dense` into
//! `<model>/dense_ov/layer_NN/`. The caller applies `mlp.global_scale`.
//!
//! Enabled by `CASCADIA_INKLING_OV_DENSE=1` (`..._DEVICE`, default `GPU`;
//! `..._PRECISION`, default `f16`). A call whose output holds a non-finite
//! value, or any device failure, returns `None` and the CPU kernel runs.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Instant;

use cascadia_ov_genai_shim::{DType, PluginConfig, Runtime};
use tracing::warn;

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct OvDenseStats {
    pub calls: u64,
    pub rows: u64,
    pub call_ns: u64,
    pub fallbacks: u64,
}

pub struct OvDense {
    dir: PathBuf, // <model>/dense_ov
    device: String,
    plugin: PluginConfig,
    hidden: usize,
    layers: Mutex<HashMap<u32, Arc<Mutex<Runtime>>>>,
    failed: Mutex<std::collections::HashSet<u32>>,
    calls: AtomicU64,
    rows: AtomicU64,
    call_ns: AtomicU64,
    fallbacks: AtomicU64,
}

fn f32_bytes(v: &[f32]) -> &[u8] {
    // SAFETY: f32 has no invalid bit patterns; lifetime tied to `v`.
    unsafe { std::slice::from_raw_parts(v.as_ptr() as *const u8, std::mem::size_of_val(v)) }
}

impl OvDense {
    /// From the environment, or `None` to keep the CPU kernel: needs
    /// `CASCADIA_INKLING_OV_DENSE` set and `<model>/dense_ov` present.
    pub fn from_env(model_dir: &Path, hidden: usize) -> Option<Self> {
        if !super::env_flag("CASCADIA_INKLING_OV_DENSE") {
            return None;
        }
        let dir = model_dir.join("dense_ov");
        if !dir.is_dir() {
            warn!(dir = %dir.display(), "CASCADIA_INKLING_OV_DENSE set but the model has no dense_ov/ dir; dense layers stay on the CPU");
            return None;
        }
        let device =
            std::env::var("CASCADIA_INKLING_OV_DENSE_DEVICE").unwrap_or_else(|_| "GPU".into());
        let precision =
            std::env::var("CASCADIA_INKLING_OV_DENSE_PRECISION").unwrap_or_else(|_| "f16".into());
        let plugin = PluginConfig::new().with("INFERENCE_PRECISION_HINT", precision);
        Some(Self {
            dir,
            device,
            plugin,
            hidden,
            layers: Mutex::new(HashMap::new()),
            failed: Mutex::new(Default::default()),
            calls: AtomicU64::new(0),
            rows: AtomicU64::new(0),
            call_ns: AtomicU64::new(0),
            fallbacks: AtomicU64::new(0),
        })
    }

    fn xml(&self, lid: u32) -> PathBuf {
        self.dir
            .join(format!("layer_{lid:02}"))
            .join("openvino_model.xml")
    }

    pub fn has_layer(&self, lid: u32) -> bool {
        self.xml(lid).is_file()
    }

    pub fn stats(&self) -> OvDenseStats {
        OvDenseStats {
            calls: self.calls.load(Ordering::Relaxed),
            rows: self.rows.load(Ordering::Relaxed),
            call_ns: self.call_ns.load(Ordering::Relaxed),
            fallbacks: self.fallbacks.load(Ordering::Relaxed),
        }
    }

    fn mark_failed(&self, lid: u32, why: &str) {
        if self.failed.lock().unwrap().insert(lid) {
            warn!(
                layer = lid,
                "inkling dense-MLP IR unusable ({why}); this layer stays on the CPU"
            );
        }
    }

    fn compiled(&self, lid: u32) -> Option<Arc<Mutex<Runtime>>> {
        if self.failed.lock().unwrap().contains(&lid) {
            return None;
        }
        let mut layers = self.layers.lock().expect("OV dense layer table lock");
        if let Some(rt) = layers.get(&lid) {
            return Some(Arc::clone(rt));
        }
        let xml = self.xml(lid);
        let Some(p) = xml.to_str() else {
            drop(layers);
            self.mark_failed(lid, "non-utf8 IR path");
            return None;
        };
        match Runtime::compile(p, &self.device, &self.plugin) {
            Ok(rt) => {
                let rt = Arc::new(Mutex::new(rt));
                layers.insert(lid, Arc::clone(&rt));
                Some(rt)
            }
            Err(e) => {
                drop(layers);
                self.mark_failed(lid, &format!("compile on {}: {e}", self.device));
                None
            }
        }
    }

    /// Compile ahead of time and take the first-shape cost of the decode
    /// bucket; `false` when the layer has to stay on the CPU.
    pub fn warm(&self, lid: u32) -> bool {
        let x = vec![0.0f32; 2 * self.hidden];
        self.forward(lid, &x, 2).is_some()
    }

    /// `down(silu(gate x) * up x)` for `rows` rows (`xs` = `[rows, hidden]`),
    /// WITHOUT `global_scale`; `None` to take the CPU kernel.
    pub fn forward(&self, lid: u32, xs: &[f32], rows: usize) -> Option<Vec<f32>> {
        debug_assert_eq!(xs.len(), rows * self.hidden);
        if rows == 0 {
            return Some(Vec::new());
        }
        let Some(rt) = self.compiled(lid) else {
            self.fallbacks.fetch_add(1, Ordering::Relaxed);
            return None;
        };
        let t0 = Instant::now();
        // The same shape buckets as the fused MoE layers: a new row count
        // costs a kernel setup, so calls use a few fixed shapes.
        let prow = super::ov_moe::bucket_rows(rows);
        let padded: Vec<f32>;
        let input = if prow != rows {
            let mut p = xs.to_vec();
            p.resize(prow * self.hidden, 0.0);
            padded = p;
            &padded[..]
        } else {
            xs
        };
        let out = {
            let mut rt = rt.lock().expect("OV dense runtime lock");
            let step = rt
                .set_input("x", DType::F32, &[1, prow, self.hidden], f32_bytes(input))
                .map_err(|e| format!("set_input x: {e}"))
                .and_then(|_| rt.infer().map_err(|e| format!("infer: {e}")));
            if let Err(why) = step {
                self.mark_failed(lid, &why);
                self.fallbacks.fetch_add(1, Ordering::Relaxed);
                return None;
            }
            match rt.output(0) {
                Ok((_, _, bytes)) => bytes
                    .chunks_exact(4)
                    .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
                    .collect::<Vec<f32>>(),
                Err(e) => {
                    self.mark_failed(lid, &format!("output: {e}"));
                    self.fallbacks.fetch_add(1, Ordering::Relaxed);
                    return None;
                }
            }
        };
        if out.len() != prow * self.hidden {
            self.mark_failed(lid, "output shape");
            self.fallbacks.fetch_add(1, Ordering::Relaxed);
            return None;
        }
        let mut out = out;
        out.truncate(rows * self.hidden);
        if out.iter().any(|v| !v.is_finite()) {
            self.fallbacks.fetch_add(1, Ordering::Relaxed);
            return None;
        }
        self.calls.fetch_add(1, Ordering::Relaxed);
        self.rows.fetch_add(rows as u64, Ordering::Relaxed);
        self.call_ns
            .fetch_add(t0.elapsed().as_nanos() as u64, Ordering::Relaxed);
        Some(out)
    }
}
