//! Golden tests for the GLM-5.2 shell primitives against fixtures generated by
//! the CPU reference (`tools/glm5_ref/gen_fixtures.py`).
//!
//! Regenerate fixtures:
//!   python tools/glm5_ref/gen_fixtures.py \
//!       --out crates/cascadia-engine-sparse-moe/tests/fixtures/glm5

use std::path::PathBuf;

use cascadia_engine_sparse_moe::dsv4::st::StFile;
use cascadia_engine_sparse_moe::glm::gate::moe_gate;

/// Open the gen_fixtures.py output, or SKIP the test (return early) when it is
/// absent. The *.safetensors fixtures are gitignored, so a fresh CI checkout
/// does not have them; they exist after running gen_fixtures.py.
macro_rules! fixtures {
    () => {{
        let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/glm5/fixtures.safetensors");
        if !p.exists() {
            eprintln!(
                "SKIP: {} absent (run tools/glm5_ref/gen_fixtures.py)",
                p.display()
            );
            return;
        }
        StFile::open(&p).expect("open fixtures")
    }};
}

/// Mixed abs/rel closeness: |a-b| <= atol + rtol*|b|. Reports worst offender.
fn assert_close(name: &str, got: &[f32], want: &[f32], atol: f32, rtol: f32) {
    assert_eq!(got.len(), want.len(), "{name}: length mismatch");
    let mut worst = (0usize, 0.0f32, 0.0f32, 0.0f32);
    for (i, (&g, &w)) in got.iter().zip(want).enumerate() {
        let d = (g - w).abs();
        let bound = atol + rtol * w.abs();
        if d > bound && d > worst.1 {
            worst = (i, d, g, w);
        }
    }
    assert!(
        worst.1 == 0.0,
        "{name}: worst diff {} at [{}]: got {} want {} (atol {atol} rtol {rtol})",
        worst.1,
        worst.0,
        worst.2,
        worst.3
    );
}

#[test]
fn moe_gate_matches_reference() {
    let fx = fixtures!();
    let (lshape, logits) = fx.f32("gate.logits").unwrap(); // [T, E]
    let (_, bias) = fx.f32("gate.bias").unwrap(); // [E]
    let (ishape, idx_want) = fx.i32("gate.idx").unwrap(); // [T, top_k]
    let (_, weight_want) = fx.f32("gate.weight").unwrap(); // [T, top_k]

    let (t, e) = (lshape[0], lshape[1]);
    let top_k = ishape[1];
    let scale = 2.5f32; // META["gate"]["scale"]

    for r in 0..t {
        let out = moe_gate(&logits[r * e..(r + 1) * e], &bias, top_k, scale, true);

        // selected expert ids must match exactly (deterministic tie-break).
        let idx_got: Vec<i32> = out.idx.iter().map(|&i| i as i32).collect();
        assert_eq!(
            idx_got,
            &idx_want[r * top_k..(r + 1) * top_k],
            "gate.idx row {r}"
        );
        // weights close (sigmoid/normalise are f32, tiny ULP drift allowed).
        assert_close(
            &format!("gate.weight[{r}]"),
            &out.weight,
            &weight_want[r * top_k..(r + 1) * top_k],
            1e-6,
            1e-5,
        );
    }
}
