//! Golden tests for the Kimi-K3 shell primitives against fixtures generated by
//! the CPU reference (`tools/kimi_k3_ref/gen_fixtures.py`), which is itself
//! validated against the vendored upstream sources.
//!
//! Regenerate fixtures:
//!   python tools/kimi_k3_ref/gen_fixtures.py \
//!       --out crates/cascadia-engine-sparse-moe/tests/fixtures/kimi_k3

use std::path::PathBuf;

use cascadia_engine_sparse_moe::dsv4::st::StFile;
use cascadia_engine_sparse_moe::glm::gate::moe_gate;
use cascadia_engine_sparse_moe::k3::{attn_res::apply_attn_res, kda, situ::situ_split};

/// Open the gen_fixtures.py output, or SKIP the test when it is absent. The
/// *.safetensors fixtures are gitignored, so a fresh checkout does not have
/// them; they exist after running gen_fixtures.py.
/// `CASCADIA_REQUIRE_FIXTURES=1` turns the skip into a failure, same as
/// k3_pipeline.rs, so a gate can demand real coverage.
macro_rules! fixtures {
    () => {{
        let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/kimi_k3/fixtures.safetensors");
        if !p.exists() {
            let msg = format!(
                "{} absent (run tools/kimi_k3_ref/gen_fixtures.py)",
                p.display()
            );
            assert!(
                std::env::var("CASCADIA_REQUIRE_FIXTURES").as_deref() != Ok("1"),
                "CASCADIA_REQUIRE_FIXTURES=1 but {msg}"
            );
            eprintln!("SKIP: {msg}");
            return;
        }
        StFile::open(&p).expect("open fixtures")
    }};
}

fn assert_close(name: &str, got: &[f32], want: &[f32], atol: f32, rtol: f32) {
    assert_eq!(got.len(), want.len(), "{name}: length mismatch");
    let mut worst = (0usize, 0.0f32, 0.0f32, 0.0f32);
    for (i, (&g, &w)) in got.iter().zip(want).enumerate() {
        let d = (g - w).abs();
        if d > atol + rtol * w.abs() && d > worst.1 {
            worst = (i, d, g, w);
        }
    }
    assert!(
        worst.1 == 0.0,
        "{name}: worst diff {} at [{}]: got {} want {} (atol {atol} rtol {rtol})",
        worst.1,
        worst.0,
        worst.2,
        worst.3
    );
}

#[test]
fn situ_matches_reference() {
    let fx = fixtures!();
    let (si, sin) = fx.f32("situ.in").expect("situ.in");
    let (_, want) = fx.f32("situ.out").expect("situ.out");
    let (rows, two_d) = (si[0], si[1]);
    let d = two_d / 2;

    let mut got = vec![0.0f32; rows * d];
    for r in 0..rows {
        situ_split(
            &sin[r * two_d..(r + 1) * two_d],
            &mut got[r * d..(r + 1) * d],
            4.0,
            Some(25.0),
        );
    }
    assert_close("situ", &got, &want, 1e-5, 1e-5);
}

#[test]
fn attn_res_matches_reference() {
    let fx = fixtures!();
    let (ps_s, ps) = fx.f32("attnres.prefix_sum").expect("prefix_sum");
    let (br_s, br) = fx.f32("attnres.block_residual").expect("block_residual");
    let (_, pw) = fx.f32("attnres.proj_w").expect("proj_w");
    let (_, nw) = fx.f32("attnres.norm_w").expect("norm_w");
    let (_, want) = fx.f32("attnres.out").expect("out");
    let (t, h, nb) = (ps_s[0], ps_s[1], br_s[1]);

    let mut got = vec![0.0f32; t * h];
    for i in 0..t {
        apply_attn_res(
            &ps[i * h..(i + 1) * h],
            &br[i * nb * h..(i + 1) * nb * h],
            &pw,
            &nw,
            1e-5,
            &mut got[i * h..(i + 1) * h],
        );
    }
    assert_close("attn_res", &got, &want, 1e-5, 1e-5);
}

#[test]
fn kda_gate_matches_reference() {
    let fx = fixtures!();
    let (gs, g_raw) = fx.f32("kdagate.g_raw").expect("g_raw");
    let (_, a_log) = fx.f32("kdagate.a_log").expect("a_log");
    let (_, dt_bias) = fx.f32("kdagate.dt_bias").expect("dt_bias");
    let (_, want) = fx.f32("kdagate.out").expect("out");
    let (t, h, d) = (gs[0], gs[1], gs[2]);

    let mut got = vec![0.0f32; t * h * d];
    for i in 0..t {
        kda::kda_gate(
            &g_raw[i * h * d..(i + 1) * h * d],
            &a_log,
            &dt_bias,
            Some(-5.0),
            h,
            d,
            &mut got[i * h * d..(i + 1) * h * d],
        );
    }
    assert_close("kda_gate", &got, &want, 1e-5, 1e-5);
}

#[test]
fn kda_recurrence_matches_reference() {
    let fx = fixtures!();
    let (qs, q) = fx.f32("kda.q").expect("q");
    let (_, k) = fx.f32("kda.k").expect("k");
    let (vs, v) = fx.f32("kda.v").expect("v");
    let (_, g) = fx.f32("kda.g").expect("g");
    let (_, beta) = fx.f32("kda.beta").expect("beta");
    let (_, st_in) = fx.f32("kda.state_in").expect("state_in");
    let (_, want_o) = fx.f32("kda.o").expect("o");
    let (_, want_s) = fx.f32("kda.state_out").expect("state_out");
    let (t, h, kd, vd) = (qs[0], qs[1], qs[2], vs[2]);

    let mut state = st_in.clone();
    let mut got = vec![0.0f32; t * h * vd];
    for i in 0..t {
        kda::kda_step(
            &q[i * h * kd..(i + 1) * h * kd],
            &k[i * h * kd..(i + 1) * h * kd],
            &v[i * h * vd..(i + 1) * h * vd],
            &g[i * h * kd..(i + 1) * h * kd],
            &beta[i * h..(i + 1) * h],
            &mut state,
            h,
            kd,
            vd,
            &mut got[i * h * vd..(i + 1) * h * vd],
        );
    }
    assert_close("kda.o", &got, &want_o, 1e-4, 1e-4);
    assert_close("kda.state_out", &state, &want_s, 1e-4, 1e-4);
}

#[test]
fn short_conv_matches_reference() {
    let fx = fixtures!();
    let (xs, x) = fx.f32("conv.x").expect("conv.x");
    let (ws, w) = fx.f32("conv.weight").expect("conv.weight");
    let (_, want_y0) = fx.f32("conv.y0").expect("y0");
    let (_, want_s0) = fx.f32("conv.state0").expect("state0");
    let (_, want_y1) = fx.f32("conv.y1").expect("y1");
    let (_, want_s1) = fx.f32("conv.state1").expect("state1");
    let (t, d, k) = (xs[0], xs[1], ws[1]);

    // fresh state
    let mut state = vec![0.0f32; d * (k - 1)];
    let mut y0 = vec![0.0f32; t * d];
    kda::short_conv(&x, &w, &mut state, d, k, &mut y0);
    assert_close("conv.y0", &y0, &want_y0, 1e-2, 1e-2);
    assert_close("conv.state0", &state, &want_s0, 1e-5, 1e-5);

    // carried state — the streaming path
    let mut y1 = vec![0.0f32; t * d];
    kda::short_conv(&x, &w, &mut state, d, k, &mut y1);
    assert_close("conv.y1", &y1, &want_y1, 1e-2, 1e-2);
    assert_close("conv.state1", &state, &want_s1, 1e-5, 1e-5);
}

#[test]
fn moe_gate_matches_reference() {
    // K3 reuses glm's router unchanged: sigmoid + noaux_tc bias, norm-topk,
    // then * routed_scaling_factor (1.0 for K3).
    let fx = fixtures!();
    let (ls, logits) = fx.f32("gate.logits").expect("logits");
    let (_, bias) = fx.f32("gate.bias").expect("bias");
    let (_, want_idx) = fx.i32("gate.idx").expect("idx");
    let (_, want_w) = fx.f32("gate.weight").expect("weight");
    let (t, e) = (ls[0], ls[1]);
    let top_k = want_w.len() / t;

    for i in 0..t {
        let out = moe_gate(&logits[i * e..(i + 1) * e], &bias, top_k, 1.0, true);
        let wi: Vec<u32> = want_idx[i * top_k..(i + 1) * top_k]
            .iter()
            .map(|&v| v as u32)
            .collect();
        assert_eq!(out.idx, wi, "gate idx row {i}");
        assert_close(
            &format!("gate.weight row {i}"),
            &out.weight,
            &want_w[i * top_k..(i + 1) * top_k],
            1e-6,
            1e-6,
        );
    }
}
