//! DeepSeek-V4-Flash (`deepseek_v4`) Rust shell
//! (see `docs/architectures/deepseek-v4.md`).
//!
//! V4's shell math (Hyper-Connections Sinkhorn mixing, sliding-window +
//! learned-compression KV, DSA indexer, attention sinks, grouped low-rank O)
//! is not traceable to OpenVINO; this module implements it in Rust, mirroring
//! the CPU reference in `tools/deepseek_v4_ref/` 1:1. Every component is
//! golden-tested against fixtures generated by that reference
//! (`tests/fixtures/dsv4/`, regenerate with
//! `tools/deepseek_v4_ref/gen_fixtures.py`).
//!
//! Numerics policy: weights and activations are held as f32; the reference's
//! bf16 rounding boundaries (after each linear / norm / rope write-back) and
//! its QAT quant-dequant sims (block FP8 e4m3 with power-of-2 scales, block
//! FP4 e2m1) are replicated exactly — the FP8/FP4/pow2 grids are bit-exact,
//! so parity with the Python reference reduces to f32 accumulation-order
//! noise, which the integration tolerances absorb.
//!
//! Build order (each lands with passing goldens):
//!   1. `math` / `rope` / `hc` / `attn` primitives   <- this milestone
//!   2. compressor (stateful decode) + indexer
//!   3. full attention layer + gate/experts + block
//!   4. runner/manifest integration (`shell_backend = "rust_dsv4"`)

pub mod attn;
pub mod attn_layer;
pub mod compress;
pub mod expert_mmap;
pub mod hc;
pub mod indexer;
pub mod loader;
pub mod math;
pub mod model;
pub mod ov_expert;
pub mod rope;
pub mod st;
pub mod stage;
